/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siapsiap;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Graphics2D;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Wahyu
 */
public class FrameProses extends javax.swing.JFrame {

    /**
     * Creates new form FrameProses
     */
    public static List<List<String>> storedListRow = new ArrayList<List<String>>();
    public static List<String> KataGabunganBaru = new ArrayList<String>();
    String[] kategoriList = new String[]{"DATA","HASIL","METODE","PROBLEM"};
    public FrameProses() throws FileNotFoundException{
        //Preferences appPrefs = Preferences.systemNodeForPackage(FrameProses.class);
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);    
         jComboKategori.removeAllItems();
         for(String string: kategoriList){
             jComboKategori.addItem(string);
         }

        jTabbedPane1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
             switch(jTabbedPane1.getSelectedIndex()){
                 case 1: 
                     break;
                default:
                    break;
             }
            }
        });
    }
    
    public static class ComboItem
    {
        private String key;
        private String value;

        public  ComboItem(String key, String value)
        {
            this.key = key;
            this.value = value;
        }

        @Override
        public String toString()
        {
            return key;
        }

        public String getKey()
        {
            return key;
        }

        public String getValue()
        {
            return value;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelURL = new javax.swing.JTextField();
        buttonBrowse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtLimitFile = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtLimitKata = new javax.swing.JTextField();
        txtNilaiK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jComboKategori = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TxtNoDataTesting = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtDekat = new javax.swing.JTextField();
        txtJauh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtHasilOutlier = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TxtNoDataTesting1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labelDurasiNB = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelDurasiKF = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelPersenKF = new javax.swing.JLabel();
        labelPersenKF2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelAkurasi = new javax.swing.JLabel();
        labelPersenKF5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelHasilNB = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        labelDurasiNB1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelDurasiKF1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelPersenKF1 = new javax.swing.JLabel();
        labelPersenKF3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelPersenKF6 = new javax.swing.JLabel();
        labelAkurasi1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelHasilNB1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("FrameProses"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        labelURL.setText("dariBuHelen.txt");

        buttonBrowse.setText("Browse");
        buttonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBrowseActionPerformed(evt);
            }
        });

        jLabel2.setText("Limit File");

        TxtLimitFile.setText("66");

        jLabel3.setText("Limit Kata");

        TxtLimitKata.setText("5400");

        txtNilaiK.setText("11");
        txtNilaiK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNilaiKActionPerformed(evt);
            }
        });

        jLabel7.setText("Nilai K");

        jButton6.setText("Pra Proses");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboKategori.setName(""); // NOI18N
        jComboKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboKategoriActionPerformed(evt);
            }
        });

        jLabel18.setText("Kategori data testing");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtLimitFile, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(txtNilaiK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtLimitKata, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboKategori, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                            .addComponent(labelURL, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBrowse))
                    .addComponent(jLabel18))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNilaiK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtLimitFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TxtLimitKata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pengaturan", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("File data testing");

        TxtNoDataTesting.setText("1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNoDataTesting, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtNoDataTesting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Naive Bayes", jPanel2);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jButton2.setText("Proses K-Fold");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 762, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("K-Fold", jPanel3);

        txtDekat.setText("3");

        txtJauh.setText("10");

        jLabel4.setText("Batas Jarak Terdekat");

        jLabel5.setText("Batas Jarak Terjauh");

        jButton3.setText("Proses Outlier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtHasilOutlier.setColumns(20);
        txtHasilOutlier.setRows(5);
        jScrollPane4.setViewportView(txtHasilOutlier);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDekat)
                            .addComponent(txtJauh, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(527, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDekat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtJauh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Outlier", jPanel4);

        jLabel6.setText("File data testing");

        TxtNoDataTesting1.setText("1");

        jButton4.setText("Proses");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane5.setViewportView(jTable2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane6.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNoDataTesting1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane6)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtNoDataTesting1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Naive Bayes 2", jPanel5);

        jButton5.setText("Proses K-Fold 2");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane7.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(0, 752, Short.MAX_VALUE))
            .addComponent(jScrollPane7)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("K-Fold 2", jPanel6);

        jLabel10.setText("Durasi Proses Perhitungan \"Naive Bayes\" = ");

        labelDurasiNB.setText("00:00:00:0000");

        jLabel12.setText("Durasi Proses Perhitungan \"K-Fold\" = ");

        labelDurasiKF.setText("00:00:00:0000");

        jLabel14.setText("Persentase K-Fold Error = ");

        labelPersenKF.setText("0");

        labelPersenKF2.setText(" %");

        jLabel16.setText("Akurasi = ");

        labelAkurasi.setText("100");

        labelPersenKF5.setText(" %");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Sebelum Proses Outlier");

        labelHasilNB.setText("Kategori terpilih banding hasil =");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHasilNB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDurasiNB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDurasiKF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPersenKF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPersenKF2))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAkurasi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPersenKF5))
                            .addComponent(jLabel8))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelDurasiNB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHasilNB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(labelDurasiKF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(labelPersenKF)
                    .addComponent(labelPersenKF2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(labelAkurasi)
                    .addComponent(labelPersenKF5))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jLabel11.setText("Durasi Proses Perhitungan \"Naive Bayes\" = ");

        labelDurasiNB1.setText("00:00:00:0000");

        jLabel13.setText("Durasi Proses Perhitungan \"K-Fold\" = ");

        labelDurasiKF1.setText("00:00:00:0000");

        jLabel15.setText("Persentase K-Fold Error = ");

        labelPersenKF1.setText("0");

        labelPersenKF3.setText(" %");

        jLabel17.setText("Akurasi = ");

        labelPersenKF6.setText(" %");

        labelAkurasi1.setText("100");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Setelah Proses Outlier");

        labelHasilNB1.setText("Kategori terpilih banding hasil =");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDurasiNB1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDurasiKF1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPersenKF1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPersenKF3))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAkurasi1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPersenKF6))
                            .addComponent(jLabel9))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(labelHasilNB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelDurasiNB1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHasilNB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(labelDurasiKF1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(labelPersenKF1)
                    .addComponent(labelPersenKF3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(labelAkurasi1)
                    .addComponent(labelPersenKF6))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Kesimpulan", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            long startTime = System.currentTimeMillis();
            updateTabel(Integer.valueOf(TxtLimitFile.getText()),Integer.valueOf(TxtNoDataTesting.getText()),Integer.valueOf(TxtLimitKata.getText()));
            long endTime = System.currentTimeMillis();

            long duration = (endTime - startTime);
            
            int seconds = (int) (duration / 1000) % 60 ;
            int minutes = (int) ((duration / (1000*60)) % 60);
            int hours   = (int) ((duration / (1000*60*60)) % 24);
            jTextArea1.append("Lama proses = " + String.valueOf(hours) + ":" + String.valueOf(minutes) + ":" + String.valueOf(seconds) + ":" + String.valueOf(duration));
            jTextArea1.append("\n");
            labelDurasiNB.setText( String.valueOf(hours) + ":" + String.valueOf(minutes) + ":" + String.valueOf(seconds) + ":" + String.valueOf(duration));
            //jTextArea1.setText(sb.toString());
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrameProses.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        long startTime = System.currentTimeMillis();
        KFold kfold = new KFold();
        KFold.Output kout = kfold.KFold(Integer.valueOf(TxtLimitFile.getText()), Integer.valueOf(txtNilaiK.getText()), Integer.valueOf(TxtLimitKata.getText()),jComboKategori.getSelectedItem().toString());
        long endTime = System.currentTimeMillis();

        long duration = (endTime - startTime);

        int seconds = (int) (duration / 1000) % 60 ;
        int minutes = (int) ((duration / (1000*60)) % 60);
        int hours   = (int) ((duration / (1000*60*60)) % 24);
        
        double persenError = kout.FError*100;
        double FError = kout.FError;
         
        
        jTextArea2.append(kout.cetak + " Error = " + String.valueOf(persenError) + "%");
        jTextArea2.append("\n"); 
        jTextArea2.append("Frekuensi error = " + FError); 
        jTextArea2.append("\n"); 
        labelPersenKF.setText(String.valueOf(persenError));
        jTextArea2.append("\n");  
        labelAkurasi.setText(String.valueOf(100-persenError));
        jTextArea2.append("\n");  
        jTextArea2.append("Lama proses = " + String.valueOf(hours) + ":" + String.valueOf(minutes) + ":" + String.valueOf(seconds) + ":" + String.valueOf(duration));
        jTextArea2.append("\n");
        labelDurasiKF.setText(String.valueOf(hours) + ":" + String.valueOf(minutes) + ":" + String.valueOf(seconds) + ":" + String.valueOf(duration));
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBrowseActionPerformed
        JFileChooser jfc = new JFileChooser();
        File workingDirectory = new File(System.getProperty("user.dir"));
        jfc.setCurrentDirectory(workingDirectory);
        jfc.showOpenDialog(null);
        File file = jfc.getSelectedFile();
        String dir = file.getAbsolutePath();
        labelURL.setText(dir);
    }//GEN-LAST:event_buttonBrowseActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(KataGabunganBaru.size()>0){
            try {
                setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                long startTime = System.currentTimeMillis();
                updateTabel2(Integer.valueOf(TxtLimitFile.getText()),Integer.valueOf(TxtNoDataTesting1.getText()),Integer.valueOf(TxtLimitKata.getText()));
                long endTime = System.currentTimeMillis();

                long duration = (endTime - startTime);

                int seconds = (int) (duration / 1000) % 60 ;
                int minutes = (int) ((duration / (1000*60)) % 60);
                int hours   = (int) ((duration / (1000*60*60)) % 24);
                jTextArea3.append("Lama proses = " + String.valueOf(hours) + ":" + String.valueOf(minutes) + ":" + String.valueOf(seconds) + ":" + String.valueOf(duration));
                jTextArea3.append("\n");
                labelDurasiNB1.setText(String.valueOf(hours) + ":" + String.valueOf(minutes) + ":" + String.valueOf(seconds) + ":" + String.valueOf(duration));
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FrameProses.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        long startTime = System.currentTimeMillis();
        KFoldSetelahOutlier kfold = new KFoldSetelahOutlier();
        KFoldSetelahOutlier.Output kout = kfold.KFold(Integer.valueOf(TxtLimitFile.getText()), Integer.valueOf(txtNilaiK.getText()), Integer.valueOf(TxtLimitKata.getText()),jComboKategori.getSelectedItem().toString());
        long endTime = System.currentTimeMillis();

        long duration = (endTime - startTime);

        int seconds = (int) (duration / 1000) % 60 ;
        int minutes = (int) ((duration / (1000*60)) % 60);
        int hours   = (int) ((duration / (1000*60*60)) % 24);
        
        double persenError = kout.FError*100;
        double FError = kout.FError;
         
        
        jTextArea4.append(kout.cetak + " Error = " + String.valueOf(persenError) + "%");
        jTextArea4.append("\n"); 
        jTextArea4.append("Frekuensi error = " + FError); 
        jTextArea4.append("\n"); 
        labelPersenKF1.setText(String.valueOf(persenError));
        jTextArea4.append("\n");  
        labelAkurasi1.setText(String.valueOf(100-persenError));
        jTextArea4.append("\n");  
        jTextArea4.append("Lama proses = " + String.valueOf(hours) + ":" + String.valueOf(minutes) + ":" + String.valueOf(seconds) + ":" + String.valueOf(duration));
        jTextArea4.append("\n");
        labelDurasiKF1.setText(String.valueOf(hours) + ":" + String.valueOf(minutes) + ":" + String.valueOf(seconds) + ":" + String.valueOf(duration));
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtNilaiKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNilaiKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNilaiKActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        SiapSiap ss = new SiapSiap();
        ss.praProses(labelURL.getText());
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Outliner oln = new Outliner();
        try {
            Outliner.Output outputOutlier = oln.Outliner(Integer.valueOf(TxtLimitFile.getText()), Integer.valueOf(txtDekat.getText()), Integer.valueOf(txtJauh.getText()), Integer.valueOf(TxtLimitKata.getText()));
            txtHasilOutlier.setText(outputOutlier.cetak);
            KataGabunganBaru = outputOutlier.KataGabunganBaru;
            //            Graphics2D g2d = (Graphics2D);
            //            for (int i = 0; i<outputOutlier.matrik.length; i++)
            //                for (int j = 0; j<outputOutlier.matrik[0].length; j++){
                //                    //do something for every field in the array
                //                    g2d.drawOval(i,j,10,10);
                //            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrameProses.class.getName()).log(Level.SEVERE, null, ex);
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameProses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameProses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameProses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameProses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {                
                    new FrameProses().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(FrameProses.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });           
        
    }
    
    
    public void updateTabel(int limitFile, int noDataTesting, int LimitKata) throws FileNotFoundException{
        
        MetaData metadata = new MetaData();
        MetaData.Output output;
            output = metadata.buatTabel(limitFile,noDataTesting,LimitKata,jComboKategori.getSelectedItem().toString());
            List<String> header = new ArrayList<String>(output.header);
            String[] col = new String[header.size()];
            col = header.toArray(col);
            DefaultTableModel modeltabel = new DefaultTableModel(col,0);
           
            storedListRow = output.listRow;
            for(int i = 0;i<output.listRow.size();i++){
                Object[] obj = output.listRow.get(i).toArray();
                modeltabel.addRow(obj);
            }
            
            jTable1.setModel(modeltabel);
            
            int lebarTabel = 0;
            
            TableColumnModel columnModel = jTable1.getColumnModel();
            for (int column = 0; column < jTable1.getColumnCount(); column++) {
            int width = 30; // Min width
//                MessageConsole mc = new MessageConsole(jTextArea1);
//                mc.redirectOut(null, System.out);
//                mc.redirectErr(Color.RED, null);
//                mc.setMessageLines(100);
                for (int row = 0; row < jTable1.getRowCount(); row++) {
                    TableCellRenderer renderer =jTable1.getCellRenderer(row, column);
                    Component comp = jTable1.prepareRenderer(renderer, row, column);
                    width = Math.max(comp.getPreferredSize().width +1 , width);
                    
                    if(Integer.valueOf(jTable1.getValueAt(row, 5) .toString())>0){
                       // table.prepareRenderer(renderer, 1, 5).setBackground(Color.red);
                    }else{
                        
                    }
                }
                if(width > 300)
                    width=300;
                columnModel.getColumn(column).setPreferredWidth(width);
                lebarTabel += width;
            }
            
            for(int i =0; i < kategoriList.length;i++){
                jTextArea1.append("P(" + kategoriList[i].toString() + "|DokUji) = " + output.hasil.get(i).toString());
                jTextArea1.append("\n");
            }
            jTextArea1.append("Kategori Terpilih " + jComboKategori.getSelectedItem().toString() + "| Hasil " + output.kelompok + " = " + String.valueOf(jComboKategori.getSelectedItem().toString()==output.kelompok));
            jTextArea1.append("\n");
            labelHasilNB.setText("Kategori Terpilih " + jComboKategori.getSelectedItem().toString() + " banding Hasil " + output.kelompok + " dengan data testing file ke " +TxtNoDataTesting.getText()+ " = " + String.valueOf(jComboKategori.getSelectedItem().toString()==output.kelompok));
    }
    
    public void updateTabel2(int limitFile, int noDataTesting, int LimitKata) throws FileNotFoundException{
        
        MetaDataSetelahOutlier metadata = new MetaDataSetelahOutlier();
        MetaDataSetelahOutlier.Output output;
            output = metadata.buatTabel(limitFile,noDataTesting,LimitKata,jComboKategori.getSelectedItem().toString());
            List<String> header = new ArrayList<String>(output.header);
            String[] col = new String[header.size()];
            col = header.toArray(col);
            DefaultTableModel modeltabel = new DefaultTableModel(col,0);
           
            storedListRow = output.listRow;
            for(int i = 0;i<output.listRow.size();i++){
                Object[] obj = output.listRow.get(i).toArray();
                modeltabel.addRow(obj);
            }
            
            jTable2.setModel(modeltabel);
            
            int lebarTabel = 0;
            
            TableColumnModel columnModel = jTable2.getColumnModel();
            for (int column = 0; column < jTable2.getColumnCount(); column++) {
            int width = 30; // Min width
//                MessageConsole mc = new MessageConsole(jTextArea1);
//                mc.redirectOut(null, System.out);
//                mc.redirectErr(Color.RED, null);
//                mc.setMessageLines(100);
                for (int row = 0; row < jTable2.getRowCount(); row++) {
                    TableCellRenderer renderer =jTable2.getCellRenderer(row, column);
                    Component comp = jTable2.prepareRenderer(renderer, row, column);
                    width = Math.max(comp.getPreferredSize().width +1 , width);
                    
                    if(Integer.valueOf(jTable2.getValueAt(row, 5) .toString())>0){
                       // table.prepareRenderer(renderer, 1, 5).setBackground(Color.red);
                    }else{
                        
                    }
                }
                if(width > 300)
                    width=300;
                columnModel.getColumn(column).setPreferredWidth(width);
                lebarTabel += width;
            }
           for(int i =0; i < kategoriList.length;i++){
                jTextArea3.append("P(" + kategoriList[i].toString() + "|DokUji) = " + output.hasil.get(i).toString());
                jTextArea3.append("\n");
            }
           
           jTextArea3.append("Kategori Terpilih " + jComboKategori.getSelectedItem().toString() + "| Hasil " + output.kelompok + " = " + String.valueOf(jComboKategori.getSelectedItem().toString()==output.kelompok));
            jTextArea3.append("\n");
            labelHasilNB1.setText("Kategori Terpilih " + jComboKategori.getSelectedItem().toString() + " banding Hasil " + output.kelompok + " dengan data testing file ke " +TxtNoDataTesting1.getText()+ " = " + String.valueOf(jComboKategori.getSelectedItem().toString()==output.kelompok));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtLimitFile;
    private javax.swing.JTextField TxtLimitKata;
    private javax.swing.JTextField TxtNoDataTesting;
    private javax.swing.JTextField TxtNoDataTesting1;
    private javax.swing.JButton buttonBrowse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel labelAkurasi;
    private javax.swing.JLabel labelAkurasi1;
    private javax.swing.JLabel labelDurasiKF;
    private javax.swing.JLabel labelDurasiKF1;
    private javax.swing.JLabel labelDurasiNB;
    private javax.swing.JLabel labelDurasiNB1;
    private javax.swing.JLabel labelHasilNB;
    private javax.swing.JLabel labelHasilNB1;
    private javax.swing.JLabel labelPersenKF;
    private javax.swing.JLabel labelPersenKF1;
    private javax.swing.JLabel labelPersenKF2;
    private javax.swing.JLabel labelPersenKF3;
    private javax.swing.JLabel labelPersenKF5;
    private javax.swing.JLabel labelPersenKF6;
    private javax.swing.JTextField labelURL;
    private javax.swing.JTextField txtDekat;
    private javax.swing.JTextArea txtHasilOutlier;
    private javax.swing.JTextField txtJauh;
    private javax.swing.JTextField txtNilaiK;
    // End of variables declaration//GEN-END:variables
}
